<?php

declare(strict_types=1);

return [

    /*
    |---------------------------------------------------------------------
    | Source paths
    |---------------------------------------------------------------------
    | Directories to scan. Only classes marked with #[TypeScript]
    | are emitted unless `scan_mode` is "all".
    */

    'paths' => [
        'models' => app_path('Models'),
        'enums' => app_path('Enums'),         // v0.2
        'form_requests' => app_path('Http/Requests'), // v0.2
        'resources' => app_path('Http/Resources'),
    ],

    /*
    | "attribute" (default) → only classes with #[TypeScript]
    | "all"                 → every class in the paths above
    */
    'scan_mode' => 'attribute',

    /*
    |---------------------------------------------------------------------
    | Output
    |---------------------------------------------------------------------
    */

    'output' => [
        'path' => resource_path('js/types/generated.ts'),
        'routes_path' => resource_path('js/types/routes.ts'),
        'style' => 'interface', // "interface" | "type"
        'banner' => "// AUTO-GENERATED by laravel-typegen — do not edit by hand.\n",
    ],

    /*
    |---------------------------------------------------------------------
    | Cast → TypeScript type map
    |---------------------------------------------------------------------
    | Extend or override defaults from CastTypeMapper.
    */

    'cast_map' => [
        // 'point'        => 'GeoPoint',
        // 'encrypted'    => 'string',
    ],

    /*
    |---------------------------------------------------------------------
    | Naming
    |---------------------------------------------------------------------
    */
    'naming' => [
        // Prefix/suffix applied to generated interface names.
        'model_prefix' => '',
        'model_suffix' => '',
        // PascalCase model class → interface name
        'transform' => 'pascal', // "pascal" | "snake" | "kebab"
    ],

    /*
    |---------------------------------------------------------------------
    | Behaviour
    |---------------------------------------------------------------------
    */
    'include_timestamps' => true,
    'include_hidden' => false, // respect $hidden
    'nullable_by_default' => false, // unless schema/cast says otherwise

    /*
    |---------------------------------------------------------------------
    | Relations wrapping
    |---------------------------------------------------------------------
    */
    'relations' => [
        'wrap_with_relation' => true,
    ],

    /*
    |---------------------------------------------------------------------
    | Generation Hooks
    |---------------------------------------------------------------------
    | Commands to run before or after generating types. The `{file}`
    | placeholder will be replaced with the output path or directory.
    |
    */
    'hooks' => [
        'pre_generate' => [
            //
        ],
        'post_generate' => [
            //
        ],
    ],
];
