<script setup lang="ts">
import { ref, onMounted } from 'vue'

const shown = ref(false)
const lines = [
  { tokens: [{ text: '// generated by laravel-typegen', color: '#636380' }] },
  { tokens: [] },
  {
    tokens: [
      { text: 'export ', color: '#3178C6' },
      { text: 'interface ', color: '#c792ea' },
      { text: 'User', color: '#fbbf24' },
      { text: ' {', color: '#6e7191' },
    ],
  },
  {
    tokens: [
      { text: '  id', color: '#f8f8f2', indent: true },
      { text: ': ', color: '#6e7191' },
      { text: 'number', color: '#FF2D20' },
      { text: ';', color: '#6e7191' },
    ],
    highlight: true,
  },
  {
    tokens: [
      { text: '  name', color: '#f8f8f2', indent: true },
      { text: ': ', color: '#6e7191' },
      { text: 'string', color: '#7ec8a4' },
      { text: ';', color: '#6e7191' },
    ],
  },
  {
    tokens: [
      { text: '  role', color: '#f8f8f2', indent: true },
      { text: ': ', color: '#6e7191' },
      { text: 'UserRole', color: '#fbbf24' },
      { text: ';', color: '#6e7191' },
    ],
  },
  {
    tokens: [
      { text: '  posts', color: '#f8f8f2', indent: true },
      { text: '?: ', color: '#6e7191' },
      { text: 'Post', color: '#fbbf24' },
      { text: '[];', color: '#6e7191' },
    ],
  },
  {
    tokens: [
      { text: '  created_at', color: '#f8f8f2', indent: true },
      { text: ': ', color: '#6e7191' },
      { text: 'string', color: '#7ec8a4' },
      { text: ';', color: '#6e7191' },
    ],
  },
  { tokens: [{ text: '}', color: '#6e7191' }] },
  { tokens: [] },
  {
    tokens: [
      { text: 'export ', color: '#3178C6' },
      { text: 'type ', color: '#c792ea' },
      { text: 'UserRole', color: '#fbbf24' },
      { text: " = 'admin' | 'member';", color: '#f1fa8c' },
    ],
  },
]

onMounted(() => {
  requestAnimationFrame(() => { shown.value = true })
})
</script>

<template>
  <div class="custom-hero" :class="{ shown }">
    <!-- Ambient mesh background -->
    <div class="mesh-bg" aria-hidden="true">
      <div class="mesh-blob mesh-blob-1" />
      <div class="mesh-blob mesh-blob-2" />
      <div class="mesh-blob mesh-blob-3" />
    </div>

    <div class="hero-inner">
      <!-- Left: copy -->
      <div class="hero-copy">
        <!-- Version badge -->
        <a
          href="https://github.com/hemilrajput/laravel-typegen/blob/main/CHANGELOG.md"
          class="version-badge"
          target="_blank"
          rel="noopener"
        >
          <span class="badge-dot" />
          <span>What's new in v2.2.3</span>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2.5 6h7M6.5 3l3 3-3 3" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </a>

        <h1 class="hero-headline">
          TypeScript types,<br>
          <span class="headline-accent">direct from Laravel</span>
        </h1>

        <p class="hero-tagline">
          One Artisan command turns your Eloquent models, Enums, FormRequests
          &amp; API Resources into fully-typed TypeScript — with AST parsing, Zod schemas,
          CI safety gates, and watch mode built in.
        </p>

        <div class="hero-actions">
          <a href="/laravel-typegen/guide/getting-started" class="btn-primary">
            Get started
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </a>
          <a href="https://github.com/hemilrajput/laravel-typegen" class="btn-secondary" target="_blank" rel="noopener">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>
            View on GitHub
          </a>
        </div>

        <!-- Social proof -->
        <div class="hero-proof">
          <div class="proof-item">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M7 1l1.55 3.14L12 4.77l-2.5 2.44.59 3.44L7 9.14 4.91 10.65l.59-3.44L3 4.77l3.45-.63L7 1z" fill="#fbbf24" stroke="#fbbf24" stroke-width="0.5" stroke-linejoin="round"/></svg>
            <span>Open source · MIT</span>
          </div>
          <span class="proof-sep">·</span>
          <div class="proof-item">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="7" r="6" stroke="currentColor" stroke-width="1.2"/><path d="M7 4v3.5l2 1.5" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/></svg>
            <span>Laravel 11, 12, 13</span>
          </div>
          <span class="proof-sep">·</span>
          <div class="proof-item">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><polyline points="2,10 5,4 8,8 10,5 12,8" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            <span>PHP 8.3+</span>
          </div>
        </div>
      </div>

      <!-- Right: code window -->
      <div class="hero-visual">
        <div class="code-window">
          <div class="window-chrome">
            <span class="dot dot-red" />
            <span class="dot dot-yellow" />
            <span class="dot dot-green" />
            <span class="window-title">generated.ts</span>
          </div>
          <div class="code-body">
            <div
              v-for="(line, i) in lines"
              :key="i"
              class="code-line"
              :class="{ 'line-highlight': line.highlight }"
            >
              <span class="line-num">{{ i + 1 }}</span>
              <span class="line-content">
                <template v-for="(tok, j) in line.tokens" :key="j">
                  <span :style="{ color: tok.color }">{{ tok.text }}</span>
                </template>
                <span v-if="i === lines.length - 1" class="cursor" />
              </span>
            </div>
          </div>
          <!-- Bottom glow -->
          <div class="window-glow" aria-hidden="true" />
        </div>

        <!-- Floating badges -->
        <div class="float-badge badge-top">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><polyline points="1,9 4,5 7,7 10,3 13,6" stroke="#22c55e" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
          54 tests passing
        </div>
        <div class="float-badge badge-bottom">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="7" r="5.5" stroke="#3178C6" stroke-width="1.2"/><path d="M5 7l1.5 1.5L9 5" stroke="#3178C6" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>
          Zero config
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* ── Container ──────────────────────────────────────────────── */
.custom-hero {
  position: relative;
  padding: 100px 24px 0;
  max-width: 1280px;
  margin: 0 auto;
  opacity: 0;
  transform: translateY(16px);
  transition: opacity 0.6s ease, transform 0.6s ease;
  overflow: hidden;
}

.custom-hero.shown {
  opacity: 1;
  transform: translateY(0);
}

/* ── Mesh background ────────────────────────────────────────── */
.mesh-bg {
  position: absolute;
  inset: -100px;
  pointer-events: none;
  z-index: 0;
}

.mesh-blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(80px);
  opacity: 0.12;
}

.mesh-blob-1 {
  width: 500px; height: 500px;
  top: -100px; left: -100px;
  background: #FF2D20;
  animation: drift 12s ease-in-out infinite alternate;
}

.mesh-blob-2 {
  width: 400px; height: 400px;
  top: 0; right: -80px;
  background: #3178C6;
  animation: drift 15s ease-in-out infinite alternate-reverse;
}

.mesh-blob-3 {
  width: 300px; height: 300px;
  bottom: 0; left: 40%;
  background: #7C3AED;
  animation: drift 10s ease-in-out infinite alternate;
}

@keyframes drift {
  from { transform: translate(0, 0) scale(1); }
  to   { transform: translate(30px, -30px) scale(1.1); }
}

/* ── Layout ─────────────────────────────────────────────────── */
.hero-inner {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 64px;
  align-items: center;
  min-height: 520px;
}

@media (max-width: 900px) {
  .hero-inner {
    grid-template-columns: 1fr;
    gap: 48px;
    text-align: center;
  }
  .custom-hero { padding-top: 60px; }
}

/* ── Version badge ──────────────────────────────────────────── */
.version-badge {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 14px;
  border-radius: 100px;
  font-size: 12.5px;
  font-weight: 500;
  color: var(--vp-c-text-2);
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-border);
  text-decoration: none;
  margin-bottom: 24px;
  transition: border-color 0.2s, color 0.2s, background 0.2s;
  letter-spacing: -0.1px;
}

.version-badge:hover {
  border-color: rgba(255, 45, 32, 0.4);
  color: var(--vp-c-text-1);
  background: var(--vp-c-bg-mute);
}

.badge-dot {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: #22c55e;
  box-shadow: 0 0 6px #22c55e;
  animation: blink 2s ease-in-out infinite;
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}

/* ── Headline ───────────────────────────────────────────────── */
.hero-headline {
  font-size: clamp(2.6rem, 5vw, 3.8rem);
  font-weight: 800;
  letter-spacing: -2.5px;
  line-height: 1.08;
  color: var(--vp-c-text-1);
  margin: 0 0 20px;
  font-feature-settings: 'cv02', 'cv11';
}

.headline-accent {
  background: linear-gradient(135deg, #FF2D20 0%, #FF6B35 50%, #fbbf24 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* ── Tagline ────────────────────────────────────────────────── */
.hero-tagline {
  font-size: 16px;
  line-height: 1.75;
  color: var(--vp-c-text-2);
  max-width: 500px;
  margin: 0 0 36px;
}

@media (max-width: 900px) {
  .hero-tagline { margin: 0 auto 36px; }
}

/* ── Buttons ────────────────────────────────────────────────── */
.hero-actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

@media (max-width: 900px) {
  .hero-actions { justify-content: center; }
}

.btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px;
  background: #FF2D20;
  color: #fff !important;
  font-size: 14px;
  font-weight: 600;
  border-radius: 10px;
  text-decoration: none;
  letter-spacing: -0.2px;
  box-shadow: 0 1px 2px rgba(255,45,32,0.3), 0 4px 16px rgba(255,45,32,0.25);
  transition: transform 0.18s ease, box-shadow 0.18s ease, filter 0.18s ease;
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 2px 4px rgba(255,45,32,0.3), 0 8px 24px rgba(255,45,32,0.35);
  filter: brightness(1.08);
}

.btn-primary:active { transform: translateY(0); }

.btn-secondary {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px;
  background: transparent;
  color: var(--vp-c-text-1) !important;
  font-size: 14px;
  font-weight: 600;
  border-radius: 10px;
  text-decoration: none;
  letter-spacing: -0.2px;
  border: 1.5px solid var(--vp-c-border);
  transition: transform 0.18s ease, border-color 0.18s ease, background 0.18s ease;
}

.btn-secondary:hover {
  transform: translateY(-2px);
  border-color: rgba(255,45,32,0.35);
  background: rgba(255,45,32,0.05);
}

/* ── Social proof ───────────────────────────────────────────── */
.hero-proof {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 28px;
  flex-wrap: wrap;
}

@media (max-width: 900px) {
  .hero-proof { justify-content: center; }
}

.proof-item {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12.5px;
  color: var(--vp-c-text-3);
  font-weight: 500;
}

.proof-sep {
  color: var(--vp-c-border);
  font-size: 14px;
}

/* ── Code window ────────────────────────────────────────────── */
.hero-visual {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
}

.code-window {
  position: relative;
  background: #0d0d14;
  border-radius: 14px;
  border: 1px solid rgba(255,255,255,0.10);
  box-shadow:
    0 0 0 1px rgba(255,255,255,0.04),
    0 24px 80px rgba(0,0,0,0.60),
    0 8px 24px rgba(0,0,0,0.40);
  overflow: hidden;
  width: 100%;
  max-width: 460px;
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  animation: float-window 7s ease-in-out infinite;
}

@keyframes float-window {
  0%, 100% { transform: translateY(0); }
  50%       { transform: translateY(-8px); }
}

.window-chrome {
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 14px 16px;
  background: #191924;
  border-bottom: 1px solid rgba(255,255,255,0.06);
}

.dot {
  width: 11px; height: 11px;
  border-radius: 50%;
}
.dot-red    { background: #ff5f57; }
.dot-yellow { background: #ffbd2e; }
.dot-green  { background: #28c840; }

.window-title {
  flex: 1;
  text-align: center;
  font-size: 11.5px;
  color: rgba(255,255,255,0.25);
  letter-spacing: 0.2px;
  font-family: inherit;
  margin-right: 60px;
}

.code-body {
  padding: 16px 0 24px;
  position: relative;
  z-index: 1;
}

.code-line {
  display: flex;
  align-items: baseline;
  gap: 0;
  min-height: 22px;
  padding: 1px 0;
  transition: background 0.2s;
}

.line-highlight {
  background: rgba(255, 45, 32, 0.10);
  border-left: 2.5px solid #FF2D20;
}

.line-num {
  display: inline-block;
  width: 40px;
  text-align: right;
  padding-right: 16px;
  font-size: 11px;
  color: rgba(255,255,255,0.18);
  user-select: none;
  flex-shrink: 0;
}

.line-content {
  font-size: 12.5px;
  line-height: 1.65;
  letter-spacing: 0.1px;
}

.cursor {
  display: inline-block;
  width: 2px;
  height: 14px;
  background: #FF2D20;
  margin-left: 2px;
  vertical-align: middle;
  border-radius: 1px;
  animation: blink-cursor 1.1s step-end infinite;
}

@keyframes blink-cursor {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}

.window-glow {
  position: absolute;
  bottom: 0; left: 0; right: 0;
  height: 80px;
  background: linear-gradient(to top, rgba(255,45,32,0.06), transparent);
  pointer-events: none;
}

/* ── Floating badges ────────────────────────────────────────── */
.float-badge {
  position: absolute;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 7px 12px;
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-border);
  border-radius: 100px;
  font-size: 12px;
  font-weight: 600;
  color: var(--vp-c-text-2);
  box-shadow: var(--shadow-md, 0 4px 16px rgba(0,0,0,0.15));
  white-space: nowrap;
  z-index: 10;
  animation: badge-float 4s ease-in-out infinite;
}

.badge-top {
  top: -16px;
  right: -12px;
  animation-delay: 0.5s;
}

.badge-bottom {
  bottom: -16px;
  left: -12px;
  animation-delay: 1.2s;
}

@keyframes badge-float {
  0%, 100% { transform: translateY(0); }
  50%       { transform: translateY(-5px); }
}
</style>
