<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'

/* ── Intersection-based reveal ─────────────────── */
const visible = ref(new Set<string>())
/* ── Terminal animation ──────────────────────────── */
const termStep = ref(-1)   // which line index is currently visible (-1 = none)
const TERM_LINES = [
  { type: 'cmd', text: 'composer require hemilrajput/laravel-typegen' },
  { type: 'ok',  text: 'Package installed successfully' },
  { type: 'gap' },
  { type: 'cmd', text: 'php artisan typegen:generate' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">User.ts</span>' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">Post.ts</span>' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">UserRole.ts</span>' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">Status.ts</span>' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">PostResource.ts</span>' },
  { type: 'ok',  text: 'Generated <span class="ct-hl">CreatePostRequest.ts</span>' },
  { type: 'done', text: 'Done in <span class="ct-hl">0.41s</span> — 12 types generated' },
]
// Delay per line index (ms) — slow enough to read each file
const TERM_DELAYS = [0, 900, 200, 600, 700, 820, 840, 900, 920, 960, 1100]

let termTimers: ReturnType<typeof setTimeout>[] = []

function startTerminal() {
  termStep.value = -1
  termTimers.forEach(clearTimeout)
  termTimers = []
  let acc = 0
  TERM_DELAYS.forEach((d, i) => {
    acc += d
    const t = setTimeout(() => { termStep.value = i }, acc)
    termTimers.push(t)
  })
  // Restart loop after all lines shown + pause
  const total = acc + 3200
  termTimers.push(setTimeout(startTerminal, total))
}

onMounted(() => {
  const io = new IntersectionObserver(
    entries => entries.forEach(e => {
      const rid = (e.target as HTMLElement).dataset.rid!
      if (e.isIntersecting) {
        visible.value.add(rid)
        if (rid === 'cta') startTerminal()
      }
    }),
    { threshold: 0.12 }
  )
  document.querySelectorAll('[data-rid]').forEach(el => io.observe(el))
})

onBeforeUnmount(() => termTimers.forEach(clearTimeout))


/* ── Before diff lines ─────────────────────────── */
const BEFORE = [
  { t: '// ⚠ maintained by hand — drifts silently', cls: 'cm' },
  { t: '', cls: '' },
  { t: 'interface User {', cls: '' },
  { t: '  id: number;',     cls: '' },
  { t: "  role: string;    // ❌ wrong type!", cls: 'del', label: '−' },
  { t: "  // created_at: missing…",            cls: 'del cm', label: '−' },
  { t: '  // posts: ???',                      cls: 'del cm', label: '−' },
  { t: '}', cls: '' },
]

const AFTER = [
  { t: '// ✦ generated by typegen:generate', cls: 'cm' },
  { t: '', cls: '' },
  { t: 'export interface User {', cls: '' },
  { t: '  id: number;',                     cls: 'add', label: '+' },
  { t: '  role: UserRole; // ✓ enum type',  cls: 'add', label: '+' },
  { t: '  created_at: string;',              cls: 'add', label: '+' },
  { t: '  posts?: Post[];',                  cls: 'add', label: '+' },
  { t: '}', cls: '' },
  { t: '', cls: '' },
  { t: "export type UserRole = 'admin' | 'member';", cls: 'add', label: '+' },
]

/* ── Features grid ─────────────────────────────── */
const FEATURES = [
  { icon: '🏗', color: '#FF2D20', bg: 'rgba(255,45,32,0.10)', tag: 'Core',
    title: 'Eloquent Models',
    desc: 'Deeply inspects casts, accessors, hidden columns, and custom Cast classes — mapped to exact TypeScript interfaces.',
  },
  { icon: '🔗', color: '#3178C6', bg: 'rgba(49,120,198,0.10)', tag: 'Smart',
    title: 'Relationship BFS',
    desc: 'Mark one model; TypeGen auto-discovers every related model via BFS graph walk, including polymorphic MorphTo unions.',
  },
  { icon: '📋', color: '#7C3AED', bg: 'rgba(124,58,237,0.10)', tag: 'Zod',
    title: 'FormRequest DTOs',
    desc: 'Parses validation rules into typed DTOs with nested dot-notation, wildcard arrays, Enum resolution, and Zod compilation.',
  },
  { icon: '🌲', color: '#059669', bg: 'rgba(5,150,105,0.10)', tag: 'AST',
    title: 'AST-Powered Resources',
    desc: 'Uses nikic/php-parser to statically analyze JsonResource toArray(). when() / whenLoaded() become optional keys automatically.',
  },
  { icon: '🛡', color: '#d97706', bg: 'rgba(217,119,6,0.10)', tag: 'Routes',
    title: 'Type-Safe Routes',
    desc: 'Inspects controller signatures to resolve route param types. Auto-increments → number, UUIDs → string. Ziggy-ready.',
  },
  { icon: '✅', color: '#0891b2', bg: 'rgba(8,145,178,0.10)', tag: 'CI/CD',
    title: 'CI --check Flag',
    desc: 'Run --check in GitHub Actions to block stale types. In-memory diff against committed files exits with code 1 on drift.',
  },
]

/* ── Stats ─────────────────────────────────────── */
const STATS = [
  { val: '54',  label: 'Tests passing', color: '#22c55e' },
  { val: '~0',  label: 'Config needed', color: '#FF2D20' },
  { val: '8',   label: 'Generators',    color: '#3178C6' },
  { val: 'MIT', label: 'License',       color: '#fbbf24' },
]
</script>

<template>
  <!-- ══════════════════════════════════════════════════════
       SECTION 1: FEATURES GRID
  ══════════════════════════════════════════════════════ -->
  <section class="feat-section" aria-label="Features">
    <div class="feat-inner">

      <!-- Section eyebrow -->
      <div class="sec-eye" data-rid="feat-eye" :class="{ vis: visible.has('feat-eye') }">
        <span class="eye-line"/><span class="eye-txt">What's included</span><span class="eye-line"/>
      </div>

      <h2 class="sec-h2" data-rid="feat-h2" :class="{ vis: visible.has('feat-h2') }">
        Everything you need.<br>
        <span class="sec-h2-muted">Nothing you don't.</span>
      </h2>

      <p class="sec-sub" data-rid="feat-sub" :class="{ vis: visible.has('feat-sub') }">
        Every Laravel-to-TypeScript bridge pattern you need — handled deeply,
        out of the box, without a single line of configuration.
      </p>

      <!-- Grid -->
      <div class="feat-grid">
        <a
          v-for="(f, i) in FEATURES"
          :key="f.title"
          href="/laravel-typegen/guide/getting-started"
          class="feat-card"
          :data-rid="`fc-${i}`"
          :class="{ vis: visible.has(`fc-${i}`) }"
          :style="{ '--delay': `${i * 70}ms` }"
        >
          <!-- Hover glow -->
          <div class="fc-glow" :style="{ background: f.color }"/>

          <div class="fc-top">
            <div class="fc-icon" :style="{ background: f.bg }">{{ f.icon }}</div>
            <span class="fc-tag" :style="{ color: f.color, background: f.bg }">{{ f.tag }}</span>
          </div>

          <h3 class="fc-title">{{ f.title }}</h3>
          <p class="fc-desc">{{ f.desc }}</p>

          <span class="fc-arrow" :style="{ color: f.color }">
            Learn more
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
              <path d="M2 6h8M7 3l3 3-3 3" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </span>
        </a>
      </div>

      <!-- Stats row -->
      <div class="stats-row">
        <div
          v-for="(s, i) in STATS" :key="s.label"
          class="stat-cell"
          :data-rid="`st-${i}`"
          :class="{ vis: visible.has(`st-${i}`) }"
          :style="{ '--delay': `${i * 80}ms` }"
        >
          <span class="stat-val" :style="{ color: s.color }">{{ s.val }}</span>
          <span class="stat-lbl">{{ s.label }}</span>
        </div>
      </div>
    </div>
  </section>

  <!-- ══════════════════════════════════════════════════════
       SECTION 2: COMPARE — BEFORE / AFTER
  ══════════════════════════════════════════════════════ -->
  <section class="compare-section" aria-label="Before and after">
    <div class="cmp-inner">

      <div class="cmp-header" data-rid="cmp-hdr" :class="{ vis: visible.has('cmp-hdr') }">
        <span class="cmp-eye">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
            <circle cx="7" cy="7" r="6" stroke="#FF2D20" stroke-width="1.2"/>
            <path d="M4.5 7l1.8 1.8L9.5 5" stroke="#FF2D20" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          The problem we solve
        </span>
        <h2 class="cmp-h2">Stop maintaining types <span class="cmp-h2-accent">twice.</span></h2>
        <p class="cmp-sub">
          Before TypeGen, every model change required a manual TypeScript update.
          One Artisan command eliminates that forever.
        </p>
      </div>

      <!-- Diff panels -->
      <div class="diff-stage" data-rid="diff" :class="{ vis: visible.has('diff') }">

        <!-- Connector line between panels -->
        <div class="diff-connector" aria-hidden="true">
          <div class="diff-conn-line"/>
          <div class="diff-conn-badge">
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
              <path d="M4 9h10M10.5 5l4 4-4 4" stroke="#FF2D20" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          <div class="diff-conn-line"/>
        </div>

        <!-- BEFORE panel -->
        <div class="diff-panel diff-before">
          <div class="diff-bar before-bar">
            <div class="diff-bar-left">
              <span class="diff-traffic r"/><span class="diff-traffic y"/><span class="diff-traffic g"/>
            </div>
            <span class="diff-filename">User.ts <span class="diff-manual">manual</span></span>
            <span class="diff-pill bad">❌ error-prone</span>
          </div>
          <div class="diff-body">
            <div v-for="(line, i) in BEFORE" :key="i" class="diff-row" :class="line.cls">
              <span class="diff-ln">{{ i + 1 }}</span>
              <span class="diff-gutter">{{ line.label || '' }}</span>
              <span class="diff-code">{{ line.t }}</span>
            </div>
          </div>
        </div>

        <!-- AFTER panel -->
        <div class="diff-panel diff-after">
          <div class="diff-bar after-bar">
            <div class="diff-bar-left">
              <span class="diff-traffic r"/><span class="diff-traffic y"/><span class="diff-traffic g"/>
            </div>
            <span class="diff-filename">User.ts <span class="diff-auto">typegen</span></span>
            <span class="diff-pill good">✓ always correct</span>
          </div>
          <div class="diff-body">
            <div v-for="(line, i) in AFTER" :key="i" class="diff-row" :class="line.cls">
              <span class="diff-ln">{{ i + 1 }}</span>
              <span class="diff-gutter">{{ line.label || '' }}</span>
              <span class="diff-code">{{ line.t }}</span>
            </div>
          </div>
        </div>

      </div><!-- /diff-stage -->

      <!-- Bottom CTA mini -->
      <div class="cmp-mini-cta" data-rid="cmp-mini" :class="{ vis: visible.has('cmp-mini') }">
        <a href="/laravel-typegen/guide/getting-started" class="cmp-cta-btn">
          Get started — it's free
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
            <path d="M3 7h8M8.5 4l3 3-3 3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </a>
        <p class="cmp-mini-note">One command. Zero configuration. Ships immediately.</p>
      </div>

    </div>
  </section>

  <!-- ══════════════════════════════════════════════════════
       SECTION 3: CTA
  ══════════════════════════════════════════════════════ -->
  <section class="cta-section" aria-label="Call to action">
    <div class="cta-inner" data-rid="cta" :class="{ vis: visible.has('cta') }">

      <!-- Background mesh -->
      <div class="cta-mesh" aria-hidden="true"/>
      <div class="cta-glow-tl" aria-hidden="true"/>
      <div class="cta-glow-br" aria-hidden="true"/>

      <!-- Terminal left -->
      <div class="cta-terminal">
        <div class="ct-bar">
          <span class="ct-dot r"/><span class="ct-dot y"/><span class="ct-dot g"/>
          <span class="ct-title">terminal</span>
        </div>
        <div class="ct-body">
          <template v-for="(line, i) in TERM_LINES" :key="i">
            <Transition name="term-line">
              <div v-if="termStep >= i">
                <!-- gap spacer -->
                <div v-if="line.type === 'gap'" class="ct-spacer"/>
                <!-- command line -->
                <div v-else-if="line.type === 'cmd'" class="ct-line">
                  <span class="ct-ps">$</span>
                  <code>{{ line.text }}</code>
                </div>
                <!-- done line -->
                <div v-else-if="line.type === 'done'" class="ct-line ct-done">
                  <span class="ct-ok">✓</span>
                  <span v-html="line.text"/>
                </div>
                <!-- ok output line -->
                <div v-else class="ct-out">
                  <span class="ct-ok">✓</span>
                  <span v-html="line.text"/>
                </div>
              </div>
            </Transition>
          </template>
          <div class="ct-cursor">
            <span class="ct-blink">▌</span>
          </div>
        </div>
      </div>

      <!-- Right content -->
      <div class="cta-content">
        <span class="cta-badge">
          <span class="cta-pulse"/>
          Open Source · Free Forever · MIT
        </span>

        <h2 class="cta-h2">
          Stop the<br>
          <span class="cta-h2-grad">type drift.</span><br>
          Start shipping.
        </h2>

        <p class="cta-p">
          Install in under 60 seconds.
          Save hours every sprint.
          Never manually update a TypeScript type again.
        </p>

        <div class="cta-btns">
          <a
            href="https://github.com/hemilrajput/laravel-typegen"
            class="cta-btn-primary"
            target="_blank" rel="noopener"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.604-3.369-1.341-3.369-1.341-.454-1.155-1.11-1.462-1.11-1.462-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.268 2.75 1.026A9.578 9.578 0 0 1 12 6.836c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.026 2.747-1.026.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.741 0 .267.18.579.688.481C19.138 20.163 22 16.418 22 12c0-5.523-4.477-10-10-10z"/>
            </svg>
            ⭐ Star on GitHub
          </a>
          <a href="/laravel-typegen/guide/getting-started" class="cta-btn-ghost">
            Read the docs →
          </a>
        </div>

        <!-- Mini stats -->
        <div class="cta-stats">
          <span class="cta-stat"><span class="cs-dot g"/> 54 tests</span>
          <span class="cta-stat"><span class="cs-dot b"/> Laravel 11–13</span>
          <span class="cta-stat"><span class="cs-dot r"/> PHP 8.3+</span>
        </div>
      </div>

    </div>
  </section>

  <!-- ══════════════════════════════════════════════════════
       FOOTER
  ══════════════════════════════════════════════════════ -->
  <footer class="tg-footer">
    <div class="footer-inner">
      <!-- Logo + tagline -->
      <div class="footer-brand">
        <div class="footer-logo">
          <svg viewBox="0 0 36 36" fill="none" width="32" height="32">
            <rect x="1" y="1" width="34" height="34" rx="9" stroke="#FF2D20" stroke-width="1.5"/>
            <text x="18" y="23" text-anchor="middle" font-family="JetBrains Mono,monospace" font-size="11" font-weight="800" fill="#FF2D20">TS</text>
          </svg>
          <span class="footer-wordmark">Laravel TypeGen</span>
        </div>
        <p class="footer-tagline">TypeScript types, direct from Laravel.</p>
        <div class="footer-socials">
          <a href="https://github.com/hemilrajput/laravel-typegen" class="footer-social" target="_blank" rel="noopener" aria-label="GitHub">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.604-3.369-1.341-3.369-1.341-.454-1.155-1.11-1.462-1.11-1.462-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.268 2.75 1.026A9.578 9.578 0 0 1 12 6.836c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.026 2.747-1.026.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.741 0 .267.18.579.688.481C19.138 20.163 22 16.418 22 12c0-5.523-4.477-10-10-10z"/>
            </svg>
          </a>
          <a href="https://packagist.org/packages/hemilrajput/laravel-typegen" class="footer-social" target="_blank" rel="noopener" aria-label="Packagist">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2L2 7v10l10 5 10-5V7L12 2zm0 2.24L20 8.5v7L12 19.76 4 15.5v-7L12 4.24z"/>
            </svg>
          </a>
        </div>
      </div>

      <!-- Links -->
      <div class="footer-links">
        <div class="footer-col">
          <div class="footer-col-title">Documentation</div>
          <a href="/laravel-typegen/guide/getting-started" class="footer-link">Getting Started</a>
          <a href="/laravel-typegen/guide/models" class="footer-link">Models</a>
          <a href="/laravel-typegen/guide/enums-and-requests" class="footer-link">Enums &amp; Requests</a>
          <a href="/laravel-typegen/guide/routes-and-dx" class="footer-link">Routes &amp; DX</a>
        </div>
        <div class="footer-col">
          <div class="footer-col-title">Project</div>
          <a href="https://github.com/hemilrajput/laravel-typegen" class="footer-link" target="_blank" rel="noopener">GitHub</a>
          <a href="https://github.com/hemilrajput/laravel-typegen/blob/main/CHANGELOG.md" class="footer-link" target="_blank" rel="noopener">Changelog</a>
          <a href="https://github.com/hemilrajput/laravel-typegen/blob/main/LICENSE" class="footer-link" target="_blank" rel="noopener">License (MIT)</a>
          <a href="https://packagist.org/packages/hemilrajput/laravel-typegen" class="footer-link" target="_blank" rel="noopener">Packagist</a>
        </div>
        <div class="footer-col">
          <div class="footer-col-title">Install</div>
          <div class="footer-cmd">
            <span class="fp">$</span>
            <code>composer require hemilrajput/laravel-typegen</code>
          </div>
          <div class="footer-cmd" style="margin-top:8px">
            <span class="fp">$</span>
            <code>php artisan typegen:generate</code>
          </div>
        </div>
      </div>
    </div>

    <!-- Bottom bar -->
    <div class="footer-bottom">
      <span>Released under the <strong>MIT License</strong>.</span>
      <span>Copyright © 2024–2026 Hemil Rajput</span>
      <span class="footer-ver">v2.2.3</span>
    </div>
  </footer>
</template>

<style scoped>
/* ══════════════════════════════════════════
   SHARED REVEAL ANIMATION
══════════════════════════════════════════ */
[data-rid] {
  opacity: 0; transform: translateY(24px);
  transition: opacity 0.65s var(--delay, 0ms) ease,
              transform 0.65s var(--delay, 0ms) cubic-bezier(0.34,1.2,0.64,1);
}
[data-rid].vis { opacity: 1; transform: translateY(0); }

/* ══════════════════════════════════════════
   SECTION 1 — FEATURES
══════════════════════════════════════════ */
.feat-section {
  padding: 120px 24px 80px;
  max-width: 1280px; margin: 0 auto;
}
.feat-inner { display: flex; flex-direction: column; align-items: center; }

/* Eye */
.sec-eye {
  display: flex; align-items: center; gap: 14px;
  font-size: 11px; font-weight: 800; letter-spacing: 1.5px;
  text-transform: uppercase; color: #FF2D20;
  margin-bottom: 20px;
}
.eye-line {
  flex: 1; height: 1px; max-width: 60px;
  background: linear-gradient(90deg, transparent, rgba(255,45,32,0.4));
}
.eye-line:first-child { transform: scaleX(-1); }
.eye-txt { white-space: nowrap; }

/* Heading */
.sec-h2 {
  font-size: clamp(2.2rem, 5vw, 3.2rem);
  font-weight: 900; letter-spacing: -3px; line-height: 1.08;
  color: var(--vp-c-text-1); text-align: center; margin: 0 0 16px;
}
.sec-h2-muted { color: var(--vp-c-text-3); }
.sec-sub {
  font-size: 16px; line-height: 1.75; color: var(--vp-c-text-2);
  max-width: 560px; text-align: center; margin: 0 0 60px;
}

/* Feature grid */
.feat-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 14px; width: 100%;
  margin-bottom: 64px;
}
@media (max-width: 900px) { .feat-grid { grid-template-columns: repeat(2,1fr); } }
@media (max-width: 560px) { .feat-grid { grid-template-columns: 1fr; } }

.feat-card {
  position: relative; overflow: hidden;
  display: flex; flex-direction: column; gap: 10px;
  padding: 26px;
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-border);
  border-radius: 18px; text-decoration: none !important;
  transition: transform 0.25s cubic-bezier(0.34,1.4,0.64,1),
              border-color 0.2s, box-shadow 0.25s;
}
.feat-card::before {
  content: '';
  position: absolute; inset: 0;
  background: linear-gradient(135deg, rgba(255,255,255,0.03) 0%, transparent 60%);
  pointer-events: none;
}
.fc-glow {
  position: absolute; top: -60px; right: -60px;
  width: 150px; height: 150px; border-radius: 50%;
  filter: blur(50px); opacity: 0;
  transition: opacity 0.35s;
  pointer-events: none;
}
.feat-card:hover .fc-glow { opacity: 0.18; }
.feat-card:hover {
  transform: translateY(-6px) scale(1.01);
  border-color: rgba(255,45,32,0.25);
  box-shadow: 0 24px 60px rgba(0,0,0,0.12), 0 6px 16px rgba(0,0,0,0.07);
}

.fc-top { display: flex; align-items: center; justify-content: space-between; }
.fc-icon {
  width: 46px; height: 46px; border-radius: 13px;
  display: flex; align-items: center; justify-content: center;
  font-size: 22px; flex-shrink: 0;
}
.fc-tag {
  font-size: 10px; font-weight: 800; letter-spacing: 0.5px;
  text-transform: uppercase; padding: 3px 10px; border-radius: 6px;
}
.fc-title {
  font-size: 15px; font-weight: 800; color: var(--vp-c-text-1);
  letter-spacing: -0.4px; line-height: 1.25; margin: 0;
}
.fc-desc {
  font-size: 13.5px; line-height: 1.68; color: var(--vp-c-text-2);
  flex: 1; margin: 0;
}
.fc-arrow {
  display: inline-flex; align-items: center; gap: 5px;
  font-size: 12.5px; font-weight: 700; margin-top: 4px;
  opacity: 0; transform: translateX(-6px);
  transition: opacity 0.18s, transform 0.18s;
}
.feat-card:hover .fc-arrow { opacity: 1; transform: translateX(0); }

/* Stats row */
.stats-row {
  display: flex; width: 100%;
  border: 1px solid var(--vp-c-border);
  border-radius: 18px; overflow: hidden;
  background: var(--vp-c-bg-soft);
}
.stat-cell {
  flex: 1; display: flex; flex-direction: column;
  align-items: center; justify-content: center; gap: 4px;
  padding: 28px 16px;
  border-right: 1px solid var(--vp-c-border);
}
.stat-cell:last-child { border-right: none; }
.stat-val {
  font-size: 2.4rem; font-weight: 900;
  letter-spacing: -2px; line-height: 1;
}
.stat-lbl {
  font-size: 11px; font-weight: 700; text-transform: uppercase;
  letter-spacing: 0.5px; color: var(--vp-c-text-3);
}
@media (max-width: 560px) {
  .stats-row { flex-wrap: wrap; }
  .stat-cell { width: 50%; min-width: 50%; border-bottom: 1px solid var(--vp-c-border); }
  .stat-cell:nth-child(2n) { border-right: none; }
}

/* ══════════════════════════════════════════
   SECTION 2 — COMPARE
══════════════════════════════════════════ */
.compare-section {
  padding: 80px 24px 100px;
  max-width: 1280px; margin: 0 auto;
}
.cmp-inner { display: flex; flex-direction: column; align-items: center; }

.cmp-header { text-align: center; margin-bottom: 52px; }
.cmp-eye {
  display: inline-flex; align-items: center; gap: 7px;
  font-size: 11.5px; font-weight: 800; letter-spacing: 1.2px;
  text-transform: uppercase; color: #FF2D20; margin-bottom: 16px;
}
.cmp-h2 {
  font-size: clamp(2rem, 4.5vw, 3rem);
  font-weight: 900; letter-spacing: -2.5px; line-height: 1.1;
  color: var(--vp-c-text-1); margin: 0 0 12px;
}
.cmp-h2-accent {
  background: linear-gradient(120deg, #FF2D20, #FF6B35);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  background-clip: text;
}
.cmp-sub {
  font-size: 15.5px; line-height: 1.75; color: var(--vp-c-text-2);
  max-width: 540px; margin: 0 auto;
}

/* Diff stage */
.diff-stage {
  width: 100%; display: flex; align-items: stretch; gap: 0;
  border-radius: 18px; overflow: hidden;
  border: 1px solid var(--vp-c-border);
  box-shadow: 0 20px 60px rgba(0,0,0,0.12), 0 4px 16px rgba(0,0,0,0.07);
  position: relative;
  animation: floatDiff 8s ease-in-out infinite;
}
@keyframes floatDiff {
  0%,100% { transform: translateY(0); }
  50%      { transform: translateY(-5px); }
}

/* Connector */
.diff-connector {
  display: flex; flex-direction: column; align-items: center;
  justify-content: center; gap: 0;
  padding: 20px 0; background: var(--vp-c-bg); z-index: 5;
  border-left: 1px solid var(--vp-c-border);
  border-right: 1px solid var(--vp-c-border);
  flex-shrink: 0; min-width: 52px;
}
.diff-conn-line {
  flex: 1; width: 1px;
  background: linear-gradient(to bottom, transparent, rgba(255,45,32,0.35), transparent);
}
.diff-conn-badge {
  width: 34px; height: 34px; border-radius: 50%;
  background: rgba(255,45,32,0.1);
  border: 1.5px solid rgba(255,45,32,0.3);
  display: flex; align-items: center; justify-content: center;
  animation: connPulse 3s ease-in-out infinite;
  flex-shrink: 0;
}
@keyframes connPulse {
  0%,100% { box-shadow: 0 0 0 0 rgba(255,45,32,0.3); }
  50%      { box-shadow: 0 0 0 8px rgba(255,45,32,0); }
}

.diff-panel {
  flex: 1;
  background: #09090f;
  font-family: 'JetBrains Mono', ui-monospace, monospace;
}
.diff-bar {
  display: flex; align-items: center; gap: 10px;
  padding: 12px 16px;
  border-bottom: 1px solid rgba(255,255,255,0.06);
  background: #101020;
}
.before-bar { background: #0d0d14; }
.after-bar  { background: #0a1018; border-bottom-color: rgba(5,150,105,0.15); }
.diff-bar-left { display: flex; gap: 6px; flex-shrink: 0; }
.diff-traffic {
  width: 10px; height: 10px; border-radius: 50%; display: inline-block;
}
.diff-traffic.r { background: #ff5f57; }
.diff-traffic.y { background: #ffbd2e; }
.diff-traffic.g { background: #28c840; }
.diff-filename {
  flex: 1; text-align: center; font-size: 12px;
  color: rgba(255,255,255,0.3); display: flex; align-items: center; justify-content: center; gap: 8px;
}
.diff-manual {
  font-size: 9px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px;
  padding: 1px 6px; border-radius: 4px;
  background: rgba(239,68,68,0.12); color: #f87171;
}
.diff-auto {
  font-size: 9px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px;
  padding: 1px 6px; border-radius: 4px;
  background: rgba(34,197,94,0.1); color: #22c55e;
}
.diff-pill {
  font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.4px;
  padding: 3px 9px; border-radius: 6px; flex-shrink: 0;
}
.diff-pill.bad  { background: rgba(239,68,68,0.12); color: #ef4444; }
.diff-pill.good { background: rgba(34,197,94,0.10); color: #22c55e; }

.diff-body { padding: 14px 0 16px; }
.diff-row {
  display: flex; align-items: baseline;
  min-height: 22px; padding: 1px 0;
}
.diff-row:hover { background: rgba(255,255,255,0.02); }
.diff-ln {
  width: 34px; text-align: right; padding-right: 10px;
  font-size: 11px; color: rgba(255,255,255,0.12); user-select: none; flex-shrink: 0;
}
.diff-gutter {
  width: 18px; flex-shrink: 0; font-size: 12px; text-align: center;
}
.diff-code {
  font-size: 12.5px; color: rgba(255,255,255,0.55); line-height: 1.75;
  white-space: pre; flex: 1; padding-right: 16px;
}

/* Diff row states */
.diff-row.del .diff-gutter { color: #ef4444; }
.diff-row.del .diff-code   { color: #f87171; background: rgba(239,68,68,0.09); }
.diff-row.del { background: rgba(239,68,68,0.06); }
.diff-row.add .diff-gutter { color: #22c55e; }
.diff-row.add .diff-code   { color: #34d399; background: rgba(5,150,105,0.09); }
.diff-row.add { background: rgba(5,150,105,0.05); }
.diff-row.cm .diff-code    { color: rgba(255,255,255,0.2); font-style: italic; }

/* Mini CTA below compare */
.cmp-mini-cta {
  margin-top: 44px; display: flex; flex-direction: column; align-items: center; gap: 12px;
}
.cmp-cta-btn {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 13px 28px; border-radius: 12px;
  background: #FF2D20; color: #fff !important;
  font-size: 14.5px; font-weight: 800; text-decoration: none;
  box-shadow: 0 4px 12px rgba(255,45,32,0.30), 0 12px 36px rgba(255,45,32,0.22);
  transition: transform 0.25s cubic-bezier(0.34,1.56,0.64,1), filter 0.2s, box-shadow 0.25s;
}
.cmp-cta-btn:hover {
  transform: translateY(-4px) scale(1.03);
  filter: brightness(1.07);
  box-shadow: 0 8px 20px rgba(255,45,32,0.38), 0 20px 48px rgba(255,45,32,0.28);
}
.cmp-mini-note { font-size: 13px; color: var(--vp-c-text-3); margin: 0; font-weight: 500; }

/* ══════════════════════════════════════════
   SECTION 3 — CTA
══════════════════════════════════════════ */
.cta-section {
  padding: 0 24px 100px;
  max-width: 1280px; margin: 0 auto;
}
.cta-inner {
  position: relative; overflow: hidden;
  display: grid; grid-template-columns: 1fr 1fr; gap: 0;
  border-radius: 24px;
  border: 1px solid var(--vp-c-border);
  background: var(--vp-c-bg-soft);
  box-shadow: 0 40px 100px rgba(0,0,0,0.14), 0 8px 28px rgba(0,0,0,0.08);
  animation: ctaFloat 12s ease-in-out infinite;
}
@keyframes ctaFloat {
  0%,100% { transform: translateY(0); }
  50%      { transform: translateY(-6px); }
}
@media (max-width: 800px) {
  .cta-inner { grid-template-columns: 1fr; }
  .cta-terminal { border-right: none; border-bottom: 1px solid var(--vp-c-border); }
}

/* Decorative background */
.cta-mesh {
  position: absolute; inset: 0; pointer-events: none;
  background-image: radial-gradient(rgba(255,255,255,0.03) 1px, transparent 1px);
  background-size: 24px 24px;
}
.cta-glow-tl {
  position: absolute; top: -80px; left: -80px;
  width: 320px; height: 320px; border-radius: 50%;
  background: radial-gradient(circle, rgba(255,45,32,0.12), transparent 70%);
  pointer-events: none; filter: blur(60px);
  animation: glowDrift 8s ease-in-out infinite alternate;
}
.cta-glow-br {
  position: absolute; bottom: -60px; right: -60px;
  width: 260px; height: 260px; border-radius: 50%;
  background: radial-gradient(circle, rgba(49,120,198,0.10), transparent 70%);
  pointer-events: none; filter: blur(50px);
  animation: glowDrift 10s ease-in-out infinite alternate-reverse;
}
@keyframes glowDrift {
  from { transform: translate(0,0); }
  to   { transform: translate(20px,-20px); }
}

/* Terminal left panel */
.cta-terminal {
  background: #09090f;
  border-right: 1px solid rgba(255,255,255,0.06);
  border-radius: 24px 0 0 24px;
  overflow: hidden;
  font-family: 'JetBrains Mono', monospace;
}
.ct-bar {
  display: flex; align-items: center; gap: 10px;
  padding: 14px 18px;
  background: #101020;
  border-bottom: 1px solid rgba(255,255,255,0.06);
}
.ct-dot {
  width: 10px; height: 10px; border-radius: 50%; display: inline-block;
}
.ct-dot.r { background: #ff5f57; }
.ct-dot.y { background: #ffbd2e; }
.ct-dot.g { background: #28c840; }
.ct-title {
  font-size: 11px; color: rgba(255,255,255,0.25);
  font-weight: 600; letter-spacing: 0.4px; text-transform: uppercase;
  margin-left: 6px;
}
.ct-body { padding: 22px 22px 24px; }
.ct-line {
  display: flex; align-items: baseline; gap: 9px;
  margin-bottom: 8px; font-size: 12.5px; color: rgba(255,255,255,0.75);
}
.ct-ps { color: #FF2D20; font-weight: 800; flex-shrink: 0; }
.ct-line code {
  background: none; padding: 0; border: none;
  font-family: inherit; font-size: inherit;
  color: rgba(255,255,255,0.75);
}
.ct-out {
  display: flex; align-items: center; gap: 8px;
  font-size: 12px; color: rgba(255,255,255,0.3);
  margin-bottom: 5px; padding-left: 4px;
}
.ct-ok { color: #22c55e; flex-shrink: 0; }
.ct-hl { color: #7ec8a4; }
.ct-spacer { height: 12px; }
.ct-done {
  margin-top: 10px; padding: 8px 12px; border-radius: 8px;
  background: rgba(34,197,94,0.07); border: 1px solid rgba(34,197,94,0.15);
  font-size: 12px; color: rgba(255,255,255,0.5);
  display: flex; align-items: center; gap: 9px;
}
.ct-cursor { margin-top: 10px; }
.ct-blink {
  color: #FF2D20; font-size: 14px;
  animation: blinkCursor 1.1s step-end infinite;
}
@keyframes blinkCursor { 0%,100% { opacity: 1; } 50% { opacity: 0; } }

/* ── Terminal line reveal transition ── */
.term-line-enter-active {
  transition: opacity 0.55s ease, transform 0.55s cubic-bezier(0.34,1.2,0.64,1);
}
.term-line-enter-from {
  opacity: 0;
  transform: translateY(8px);
}
.term-line-leave-active { transition: opacity 0.25s ease; }
.term-line-leave-to     { opacity: 0; }

/* Right content */
.cta-content {
  display: flex; flex-direction: column;
  padding: 48px 44px; position: relative; z-index: 1;
}
.cta-badge {
  display: inline-flex; align-items: center; gap: 8px;
  font-size: 12px; font-weight: 700;
  color: var(--vp-c-text-2);
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-border);
  padding: 5px 14px; border-radius: 100px;
  margin-bottom: 28px; align-self: flex-start;
}
.cta-pulse {
  width: 7px; height: 7px; border-radius: 50%; background: #22c55e;
  animation: pulseBadge 2.4s ease infinite; flex-shrink: 0;
}
@keyframes pulseBadge {
  0%   { box-shadow: 0 0 0 0 rgba(34,197,94,0.7); }
  70%  { box-shadow: 0 0 0 7px rgba(34,197,94,0); }
  100% { box-shadow: 0 0 0 0 rgba(34,197,94,0); }
}

.cta-h2 {
  font-size: clamp(2.2rem, 4vw, 3.4rem);
  font-weight: 900; letter-spacing: -3px; line-height: 1.08;
  color: var(--vp-c-text-1); margin: 0 0 16px;
}
.cta-h2-grad {
  background: linear-gradient(120deg, #FF2D20 0%, #FF6B35 50%, #fbbf24 100%);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  background-clip: text;
  animation: gradShimmer 4s ease infinite; background-size: 200% auto;
}
@keyframes gradShimmer {
  0%,100% { background-position: 0% center; }
  50%      { background-position: 100% center; }
}
.cta-p {
  font-size: 15.5px; line-height: 1.78; color: var(--vp-c-text-2);
  margin: 0 0 32px;
}

.cta-btns { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 28px; }
.cta-btn-primary {
  position: relative; overflow: hidden;
  display: inline-flex; align-items: center; gap: 9px;
  padding: 13px 26px; border-radius: 12px;
  background: linear-gradient(135deg, #FF2D20, #d92619);
  color: #fff !important; font-size: 14px; font-weight: 800;
  text-decoration: none;
  box-shadow: 0 2px 8px rgba(255,45,32,0.32), 0 10px 32px rgba(255,45,32,0.25);
  transition: transform 0.25s cubic-bezier(0.34,1.56,0.64,1), filter 0.2s, box-shadow 0.25s;
}
.cta-btn-primary:hover {
  transform: translateY(-4px) scale(1.03);
  filter: brightness(1.07);
  box-shadow: 0 6px 14px rgba(255,45,32,0.38), 0 18px 44px rgba(255,45,32,0.30);
}
.cta-btn-ghost {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 13px 24px; border-radius: 12px;
  background: transparent; color: var(--vp-c-text-1) !important;
  font-size: 14px; font-weight: 700; text-decoration: none;
  border: 1.5px solid var(--vp-c-border);
  transition: transform 0.25s cubic-bezier(0.34,1.56,0.64,1), border-color 0.2s, background 0.2s;
}
.cta-btn-ghost:hover {
  transform: translateY(-4px) scale(1.02);
  border-color: rgba(255,45,32,0.35);
  background: rgba(255,45,32,0.05);
}

.cta-stats { display: flex; gap: 18px; flex-wrap: wrap; }
.cta-stat {
  display: flex; align-items: center; gap: 7px;
  font-size: 12.5px; font-weight: 600; color: var(--vp-c-text-3);
}
.cs-dot { width: 6px; height: 6px; border-radius: 50%; display: inline-block; }
.cs-dot.g { background: #22c55e; }
.cs-dot.b { background: #3178C6; }
.cs-dot.r { background: #FF2D20; }

/* ══════════════════════════════════════════
   FOOTER
══════════════════════════════════════════ */
.tg-footer {
  border-top: 1px solid var(--vp-c-border);
  background: var(--vp-c-bg-soft);
  padding-top: 60px;
}
.footer-inner {
  max-width: 1280px; margin: 0 auto;
  padding: 0 24px 48px;
  display: grid; grid-template-columns: 260px 1fr; gap: 60px;
}
@media (max-width: 760px) {
  .footer-inner { grid-template-columns: 1fr; gap: 40px; }
}

/* Brand */
.footer-brand {}
.footer-logo {
  display: flex; align-items: center; gap: 10px; margin-bottom: 12px;
}
.footer-wordmark {
  font-size: 15px; font-weight: 800; color: var(--vp-c-text-1);
  letter-spacing: -0.5px;
}
.footer-tagline {
  font-size: 13.5px; color: var(--vp-c-text-3); line-height: 1.6;
  margin: 0 0 18px;
}
.footer-socials { display: flex; gap: 10px; }
.footer-social {
  width: 36px; height: 36px; border-radius: 9px;
  border: 1px solid var(--vp-c-border);
  background: var(--vp-c-bg);
  color: var(--vp-c-text-2);
  display: flex; align-items: center; justify-content: center;
  text-decoration: none; transition: border-color 0.15s, color 0.15s, transform 0.2s;
}
.footer-social:hover { color: #FF2D20; border-color: rgba(255,45,32,0.35); transform: translateY(-2px); }

/* Links grid */
.footer-links {
  display: grid; grid-template-columns: repeat(3,1fr); gap: 32px;
}
@media (max-width: 600px) { .footer-links { grid-template-columns: 1fr 1fr; } }

.footer-col { display: flex; flex-direction: column; gap: 10px; }
.footer-col-title {
  font-size: 11px; font-weight: 800; text-transform: uppercase;
  letter-spacing: 0.8px; color: var(--vp-c-text-3); margin-bottom: 4px;
}
.footer-link {
  font-size: 13.5px; font-weight: 500; color: var(--vp-c-text-2);
  text-decoration: none; transition: color 0.15s;
}
.footer-link:hover { color: #FF2D20; }

.footer-cmd {
  display: flex; align-items: flex-start; gap: 7px;
  font-family: 'JetBrains Mono', monospace;
  font-size: 11.5px; color: var(--vp-c-text-2);
  background: var(--vp-c-bg); border: 1px solid var(--vp-c-border);
  border-radius: 8px; padding: 9px 12px;
  line-height: 1.5; word-break: break-all;
}
.fp { color: #FF2D20; font-weight: 700; flex-shrink: 0; }
.footer-cmd code { background: none; padding: 0; border: none; font-family: inherit; font-size: inherit; }

/* Bottom bar */
.footer-bottom {
  border-top: 1px solid var(--vp-c-border);
  padding: 18px 24px;
  max-width: 1280px; margin: 0 auto;
  display: flex; align-items: center; gap: 20px; flex-wrap: wrap;
  font-size: 12.5px; color: var(--vp-c-text-3);
}
.footer-ver {
  margin-left: auto;
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px; font-weight: 700;
  color: #FF2D20; background: rgba(255,45,32,0.08);
  padding: 2px 10px; border-radius: 6px;
  border: 1px solid rgba(255,45,32,0.18);
}
</style>
